import {
  Users,
  Calendar,
  ReceiptText,
  Package,
  Banknote,
  Cpu,
  CreditCard,
  BedDouble,
  Wrench,
  ShieldAlert,
  FileText,
  Archive,
} from "lucide-react";

/**
 * Retention period for archived items in days before auto permanent deletion.
 * Configurable here across the entire application.
 */
export const ARCHIVE_RETENTION_DAYS = 30;

/**
 * Entity Types configuration with icons, labels, badges and color accents
 */
export const ARCHIVE_ENTITY_CONFIG = {
  all: {
    key: "all",
    label: "الكل",
    icon: Archive,
    color: "text-primary",
    bgColor: "bg-primary/10",
    borderColor: "border-primary/20",
  },
  patient: {
    key: "patient",
    label: "المرضى",
    singularLabel: "مريض",
    collectionKey: "patients",
    icon: Users,
    color: "text-sky-500",
    bgColor: "bg-sky-500/10",
    borderColor: "border-sky-500/25",
    badgeColor: "bg-sky-50 text-sky-700 dark:bg-sky-950/60 dark:text-sky-300 border-sky-200 dark:border-sky-800/40",
  },
  appointment: {
    key: "appointment",
    label: "المواعيد",
    singularLabel: "موعد",
    collectionKey: "appointments",
    icon: Calendar,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10",
    borderColor: "border-teal-500/25",
    badgeColor: "bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300 border-teal-200 dark:border-teal-800/40",
  },
  invoice: {
    key: "invoice",
    label: "الفواتير",
    singularLabel: "فاتورة",
    collectionKey: "invoices",
    icon: ReceiptText,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/25",
    badgeColor: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/40",
  },
  package: {
    key: "package",
    label: "الباقات",
    singularLabel: "باقة علاجية",
    collectionKey: "package-templates",
    icon: Package,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/25",
    badgeColor: "bg-purple-50 text-purple-700 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-800/40",
  },
  expense: {
    key: "expense",
    label: "المصروفات",
    singularLabel: "مصروف",
    collectionKey: "expenses",
    icon: Banknote,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10",
    borderColor: "border-rose-500/25",
    badgeColor: "bg-rose-50 text-rose-700 dark:bg-rose-950/60 dark:text-rose-300 border-rose-200 dark:border-rose-800/40",
  },
  device: {
    key: "device",
    label: "الأجهزة",
    singularLabel: "جهاز طبي",
    collectionKey: "devices",
    icon: Cpu,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/25",
    badgeColor: "bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300 border-blue-200 dark:border-blue-800/40",
  },
  service: {
    key: "service",
    label: "الخدمات",
    singularLabel: "خدمة",
    collectionKey: "services",
    icon: CreditCard,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/25",
    badgeColor: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/40",
  },
  room: {
    key: "room",
    label: "الغرف",
    singularLabel: "غرفة علاج",
    collectionKey: "rooms",
    icon: BedDouble,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/25",
    badgeColor: "bg-amber-50 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-800/40",
  },
  maintenance: {
    key: "maintenance",
    label: "الصيانة",
    singularLabel: "طلب صيانة",
    collectionKey: "maintenance",
    icon: Wrench,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/25",
    badgeColor: "bg-orange-50 text-orange-700 dark:bg-orange-950/60 dark:text-orange-300 border-orange-200 dark:border-orange-800/40",
  },
  followup: {
    key: "followup",
    label: "المتابعات",
    singularLabel: "متابعة غائب",
    collectionKey: "follow_ups",
    icon: ShieldAlert,
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    borderColor: "border-cyan-500/25",
    badgeColor: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/60 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800/40",
  },
  note: {
    key: "note",
    label: "الملاحظات",
    singularLabel: "ملاحظة سريرية",
    collectionKey: "internal_notes",
    icon: FileText,
    color: "text-violet-500",
    bgColor: "bg-violet-500/10",
    borderColor: "border-violet-500/25",
    badgeColor: "bg-violet-50 text-violet-700 dark:bg-violet-950/60 dark:text-violet-300 border-violet-200 dark:border-violet-800/40",
  },
};

export const ARCHIVE_SORT_OPTIONS = [
  { value: "newest", label: "الأحدث أرشفة" },
  { value: "oldest", label: "الأقدم أرشفة" },
  { value: "expiring_soon", label: "الأقرب للحذف النهائي" },
];
