import { apiRequest } from "../api/client";

export const ACTIVITY_ACTIONS = {
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_UPDATED: "INVOICE_UPDATED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_METHOD_CHANGED: "PAYMENT_METHOD_CHANGED",
  INVOICE_ARCHIVED: "INVOICE_ARCHIVED",
  INVOICE_RESTORED: "INVOICE_RESTORED",
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_ARCHIVED: "EXPENSE_ARCHIVED",
  EXPENSE_RESTORED: "EXPENSE_RESTORED",
  MAINTENANCE_EXPENSE_CREATED: "MAINTENANCE_EXPENSE_CREATED",
  MAINTENANCE_EXPENSE_UPDATED: "MAINTENANCE_EXPENSE_UPDATED",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_ENDED: "SESSION_ENDED",
  SESSION_CANCELLED: "SESSION_CANCELLED",
  SESSION_UPDATED: "SESSION_UPDATED",
  CLINICAL_NOTES_UPDATED: "CLINICAL_NOTES_UPDATED",
  PRESCRIPTION_SAVED: "PRESCRIPTION_SAVED",
  ROOM_ASSIGNED: "ROOM_ASSIGNED",
  BED_ASSIGNED: "BED_ASSIGNED",
  PACKAGE_SESSION_DEDUCTED: "PACKAGE_SESSION_DEDUCTED",
  PACKAGE_ASSIGNED: "PACKAGE_ASSIGNED",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  TEAM_MEMBER_UPDATED: "TEAM_MEMBER_UPDATED",
  TEAM_MEMBER_ACCOUNT_STATUS_CHANGED: "TEAM_MEMBER_ACCOUNT_STATUS_CHANGED",
};

export const ACTIVITY_ACTION_LABELS = {
  [ACTIVITY_ACTIONS.INVOICE_CREATED]: "إنشاء فاتورة",
  [ACTIVITY_ACTIONS.INVOICE_UPDATED]: "تحديث فاتورة",
  [ACTIVITY_ACTIONS.PAYMENT_RECORDED]: "تسجيل دفعة",
  [ACTIVITY_ACTIONS.PAYMENT_METHOD_CHANGED]: "تغيير طريقة الدفع",
  [ACTIVITY_ACTIONS.INVOICE_ARCHIVED]: "أرشفة فاتورة",
  [ACTIVITY_ACTIONS.INVOICE_RESTORED]: "استعادة فاتورة",
  [ACTIVITY_ACTIONS.EXPENSE_CREATED]: "إضافة مصروف",
  [ACTIVITY_ACTIONS.EXPENSE_UPDATED]: "تحديث مصروف",
  [ACTIVITY_ACTIONS.EXPENSE_ARCHIVED]: "أرشفة مصروف",
  [ACTIVITY_ACTIONS.EXPENSE_RESTORED]: "استعادة مصروف",
  [ACTIVITY_ACTIONS.MAINTENANCE_EXPENSE_CREATED]: "مصروف صيانة تلقائي",
  [ACTIVITY_ACTIONS.MAINTENANCE_EXPENSE_UPDATED]: "تحديث مصروف الصيانة",
  [ACTIVITY_ACTIONS.SESSION_STARTED]: "بدء الجلسة",
  [ACTIVITY_ACTIONS.SESSION_ENDED]: "إنهاء الجلسة",
  [ACTIVITY_ACTIONS.SESSION_CANCELLED]: "إلغاء الجلسة",
  [ACTIVITY_ACTIONS.SESSION_UPDATED]: "تحديث الجلسة",
  [ACTIVITY_ACTIONS.CLINICAL_NOTES_UPDATED]: "تحديث التوثيق السريري",
  [ACTIVITY_ACTIONS.PRESCRIPTION_SAVED]: "حفظ روشتة",
  [ACTIVITY_ACTIONS.ROOM_ASSIGNED]: "تعيين غرفة",
  [ACTIVITY_ACTIONS.BED_ASSIGNED]: "تعيين سرير",
  [ACTIVITY_ACTIONS.PACKAGE_SESSION_DEDUCTED]: "خصم جلسة من باقة",
  [ACTIVITY_ACTIONS.PACKAGE_ASSIGNED]: "اشتراك في باقة",
  [ACTIVITY_ACTIONS.TEAM_MEMBER_ADDED]: "إضافة عضو فريق",
  [ACTIVITY_ACTIONS.TEAM_MEMBER_UPDATED]: "تحديث بيانات عضو فريق",
  [ACTIVITY_ACTIONS.TEAM_MEMBER_ACCOUNT_STATUS_CHANGED]: "تغيير حالة حساب عضو فريق",
};

export async function logActivity({ action, actorUserId, patientId, entityType, entityId, details }) {
  try {
    await apiRequest("/audit_logs", {
      method: "POST",
      body: JSON.stringify({
        action,
        actor_user_id: actorUserId ?? null,
        patient_id: patientId ?? null,
        entity_type: entityType,
        entity_id: entityId,
        details: details ?? null,
        created_at: new Date().toISOString(),
      }),
    });
  } catch (error) {
    console.error("فشل تسجيل النشاط:", error);
  }
}
