import {
  CalendarCheck,
  CheckCircle2,
  Percent,
  Clock,
  Activity,
  Stethoscope,
  UserCog,
  BedDouble,
  DoorOpen,
  Wrench,
  UserPlus,
  Gauge,
} from "lucide-react";

export function buildPulseStatItems(kpis) {
  return [
    {
      key: "todaysAppointments",
      label: "مواعيد اليوم",
      value: kpis.todaysAppointments,
      icon: CalendarCheck,
      iconWrapperClassName: "bg-primary/10 text-primary",
    },
    {
      key: "todaysCompleted",
      label: "مكتملة اليوم",
      value: kpis.todaysCompleted,
      icon: CheckCircle2,
      valueClassName: "text-emerald-600",
      iconWrapperClassName: "bg-emerald-500/10 text-emerald-600",
    },
    {
      key: "completionRate",
      label: "نسبة الإنجاز اليوم",
      value: kpis.completionRate,
      suffix: "%",
      icon: Percent,
      valueClassName: "text-emerald-600",
      iconWrapperClassName: "bg-emerald-500/10 text-emerald-600",
    },
    {
      key: "waitingNow",
      label: "في الانتظار الآن",
      value: kpis.waitingNow,
      icon: Clock,
      valueClassName: "text-amber-500",
      iconWrapperClassName: "bg-amber-500/10 text-amber-500",
    },
    {
      key: "inSessionNow",
      label: "في الجلسة الآن",
      value: kpis.inSessionNow,
      icon: Activity,
      valueClassName: "text-cyan-600",
      iconWrapperClassName: "bg-cyan-500/10 text-cyan-600",
    },
    {
      key: "availableDoctors",
      label: "أطباء متاحون",
      value: `${kpis.availableDoctors}/${kpis.totalDoctors}`,
      icon: Stethoscope,
      valueClassName: "text-indigo-600",
      iconWrapperClassName: "bg-indigo-500/10 text-indigo-600",
    },
    {
      key: "busyDoctors",
      label: "أطباء مشغولون",
      value: kpis.busyDoctors,
      icon: UserCog,
      valueClassName: "text-rose-600",
      iconWrapperClassName: "bg-rose-500/10 text-rose-600",
    },
    {
      key: "availableRooms",
      label: "غرف متاحة",
      value: `${kpis.availableRooms}/${kpis.totalRooms}`,
      icon: DoorOpen,
      valueClassName: "text-emerald-600",
      iconWrapperClassName: "bg-emerald-500/10 text-emerald-600",
    },
    {
      key: "occupiedRooms",
      label: "غرف مشغولة",
      value: kpis.occupiedRooms,
      icon: BedDouble,
      valueClassName: "text-rose-600",
      iconWrapperClassName: "bg-rose-500/10 text-rose-600",
    },
    {
      key: "devicesNeedingMaintenance",
      label: "أجهزة بحاجة صيانة",
      value: kpis.devicesNeedingMaintenance,
      icon: Wrench,
      valueClassName: "text-amber-600",
      iconWrapperClassName: "bg-amber-500/10 text-amber-600",
    },
    {
      key: "newPatientsToday",
      label: "مرضى جدد اليوم",
      value: kpis.newPatientsToday,
      icon: UserPlus,
      valueClassName: "text-violet-600",
      iconWrapperClassName: "bg-violet-500/10 text-violet-600",
    },
    {
      key: "workloadLevel",
      label: "مستوى الحمل الحالي",
      value: kpis.workloadLevel,
      icon: Gauge,
      valueClassName: "text-foreground",
      iconWrapperClassName: "bg-muted text-foreground",
    },
  ];
}

export const STATUS_TONE_CLASSES = {
  normal: "bg-emerald-500/10 text-emerald-600 border-emerald-500/30",
  busy: "bg-amber-500/10 text-amber-600 border-amber-500/30",
  critical: "bg-destructive/10 text-destructive border-destructive/30",
};
