import {
  Users,
  CalendarCheck,
  Activity,
  DollarSign,
  Clock,
  Stethoscope,
  UserCog,
  DoorOpen,
  Wrench,
  Percent,
} from "lucide-react";

// إعداد بطاقات مؤشرات الأداء الرئيسية لنبض المركز، مع تفعيل الاتجاه والمخطط المصغر فقط
// حيث تتوفر بيانات زمنية حقيقية تدعمها (وليس لكل بطاقة بشكل تعسفي)
export function buildPulseKpiCards(kpis, charts) {
  return [
    {
      key: "patientsToday",
      label: "المرضى اليوم",
      value: kpis.patientsToday,
      description: "مرضى فريدون تمت رؤيتهم اليوم",
      icon: Users,
      color: "blue",
      trend: kpis.trends.patientsToday,
      sparklineData: charts.arrivalsToday,
    },
    {
      key: "appointmentsToday",
      label: "مواعيد اليوم",
      value: kpis.appointmentsToday,
      description: "إجمالي المواعيد المجدولة اليوم",
      icon: CalendarCheck,
      color: "purple",
      trend: kpis.trends.appointmentsToday,
      sparklineData: charts.appointmentsToday,
    },
    {
      key: "activeSessions",
      label: "جلسات نشطة الآن",
      value: kpis.activeSessionsNow,
      description: "مرضى داخل جلسات علاجية حالياً",
      icon: Activity,
      color: "cyan",
      sparklineData: charts.doctorWorkloadToday,
    },
    {
      key: "revenueToday",
      label: "إيرادات اليوم",
      value: kpis.revenueToday,
      suffix: "ج.م",
      description: "إجمالي المدفوعات المحصّلة اليوم",
      icon: DollarSign,
      color: "emerald",
      trend: kpis.trends.revenueToday,
    },
    {
      key: "waitingNow",
      label: "في الانتظار الآن",
      value: kpis.waitingNow,
      description: `متوسط الانتظار ${kpis.avgWaitingMinutes} دقيقة`,
      icon: Clock,
      color: "amber",
      sparklineData: charts.waitingQueueToday,
    },
    {
      key: "availableDoctors",
      label: "أطباء متاحون",
      value: `${kpis.availableDoctors}/${kpis.totalDoctors}`,
      description: "جاهزون لاستقبال مرضى جدد",
      icon: Stethoscope,
      color: "teal",
    },
    {
      key: "busyDoctors",
      label: "أطباء مشغولون",
      value: kpis.busyDoctors,
      description: "داخل جلسة علاجية حالياً",
      icon: UserCog,
      color: "pink",
    },
    {
      key: "occupiedRooms",
      label: "غرف مشغولة",
      value: `${kpis.occupiedRooms}/${kpis.totalRooms}`,
      description: "من إجمالي غرف المركز",
      icon: DoorOpen,
      color: "indigo",
    },
    {
      key: "devicesMaintenance",
      label: "أجهزة بحاجة صيانة",
      value: kpis.devicesNeedingMaintenance,
      description: "تحتاج متابعة فنية",
      icon: Wrench,
      color: "red",
    },
    {
      key: "completionRate",
      label: "نسبة الإنجاز اليوم",
      value: kpis.completionRateToday,
      suffix: "%",
      description: `${kpis.completedToday} مكتمل من ${kpis.appointmentsToday}`,
      icon: Percent,
      color: "purple",
      trend: kpis.trends.completedToday,
    },
  ];
}
